name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  bloc: ^9.0.0
  carousel_slider: ^5.1.1
  dartz: ^0.10.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^3.1.0
  get_it: 8.2.0
  go_router: ^15.1.2
  google_sign_in: ^6.3.0
  http: ^1.6.0
  injectable: 2.5.1
  intl: ^0.20.2
  ionicons: ^0.2.2
  json_annotation: ^4.9.0
  sizer: ^3.0.5
  supabase_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.3
  injectable_generator: ^2.7.0
  change_app_package_name: ^1.5.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 

flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - .env.prod
  fonts:
    - family: Formula1Bold
      fonts:
        - asset: assets/fonts/Formula1-Bold.otf

    - family: Formula1Regular
      fonts:
        - asset: assets/fonts/Formula1-Regular.otf

    - family: Formula1Wide
      fonts:
        - asset: assets/fonts/Formula1-Wide.otf
